### PR TITLE
Add hv/vhv corps, cherry vs base

### PR DESCRIPTION
**Pull request by lashtear**
This is the hv/vhv corps change under discussion, with art from @OmegaHaxors.  Still needs recipes added.

### CODE REVIEW

**Comment by jrddunbr** [comment]
Are we waiting for more crafting materials from @OmegaHaxors, or do you want me to come up with some recipes? I will download and test to see if they work in a reasonable manner.

**Comment by lashtear** [comment]
Checking on furnace, I see

https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/java/mods/eln/transparentnode/electricalfurnace/ElectricalFurnaceElement.java#L168

...e.g. it should (when empty) be a high impedance 100kV device.

Will try to duplicate your situation there, but I haven't so far.

**Comment by jrddunbr** [comment]
Hmm, noted. It may have just been user error, when I placed it and connected it to power with a current limiting relay circuit set to cap at 4A, the relay clicked once or twice, and then it was fine. So whatever it is, perhaps it's just a small peak (enough to explode?) and not quite a dead short.

**Comment by OmegaHaxors** [comment]
Just add recipes for each which contains 2 of the previous tier tungsten corp to make the next one.

**Pull request merged**
