### PR TITLE
Devel shaft objects

### PR DESCRIPTION
**Pull request by jrddunbr**
This is gonna need a rebase.

Addresses #14

### CODE REVIEW

**Comment by jrddunbr** [comment]
The lang file has problems. The thing that parses the source to find things is borked and automatically obliterate the language file for you. (not a feature)

**Comment by Grissess** [comment]
Ah, that doesn't run on my laptop because it seems to be an idiosyncracy of runClient. I thought it was convenient to not have to name things :)

Do you just want to revert the lang file and manually add the shaft motor name?

**Comment by jrddunbr** [comment]
Revert the automatic changes to the lang file, and **do not build or run before committing changes**. It will obliterate the lang file.

**Comment by jrddunbr** [comment]
Verifying core functionality...

**Comment by jrddunbr** [comment]
In my test world, I was able to push in 1.6kW on the motor and get out 2kW from the generator...
not quite balanced yet..

**Pull request merged**
