### PR TITLE
Update src/main/resources/assets/eln/lang/de_DE.txt

### PR DESCRIPTION
**Pull request by pyramidenkoenig**
Updated and reviewed the german translation.

### CODE REVIEW

**Comment by jrddunbr** [comment]
Thank you for updating the translations! This is a great start, and as-is will be an improvement over the existing file.

Unfortunately, this file doesn't look completed, compared to the following canonical language file:

https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/resources/assets/eln/lang/en_US.lang

Notice that the length of the files is different (>300 lines more in the `en_US.lang` file). What I would suggest doing is the following:

* Take the `en_US.lang` file, and then changing the text on the right side of the equal sign (the translation fields) to German, using the translations from the old `de_DE.lang` file. Add new translation entries as needed for new entries as you need. All of the lines on the left of the equal sign that are not comments should be **exactly** the same as in the `en_US.lang` file.
* Remove old translations as removed from the `en_US.lang` file (old translations are no longer used, but can be left in for backwards compatibility if desired)

For example, let's say we have the language files:

en_US.lang | de_DE.lang | old de_DE.lang | pt_BR.lang
--- | --- | --- | ---
item=Item | item=[German translation] | (nonexistant) | item=[Brazilian translation]
another_item=Another Item | another_item=[German translation] | another_item=[German translation] | another_item=[Brazilian translation]

and so on. Notice that we added a new line from the `en_US.lang` file to the `de_DE.lang` file that was not previously there. That happens when translations are modified or when new items, blocks, or functionality are added to the mod. On both lines, we will see the name of the item (typically in English) with escape codes that matches the actual source code, and on the right, we find the translation: the line on the left of the `=` sign will always be the same across all language files, the only thing that should be changing is the translation.

In addition, if there are notable locations where the language file causes a particular phrase to not make sense (for example, out of order), that would be good to note somewhere. 

I intend to (eventually) make a helper program to use (written most likely in Python) whose task it is to find these untranslated items and such and help you track them down in the hundreds of lines of translations.

**Comment by jrddunbr** [comment]
Also, as submitted, I can't accept this PR, because the file extension must be `de_DE.lang`, not `de_DE.txt`. I'm willing to pull this translation file in, but the extension has to be correct so that it overwrites the old file properly on the source code tree.

I can also just convert the extension and modify the pull request if you can't.

**Comment by pyramidenkoenig** [comment]
Sorry for the mess, It's been a while since i used github the last time ;)
Im gonna start translating those extra 300 lines soon.

**Comment by jrddunbr** [comment]
OK, neat. This is possible to merge.

Let me know if you'd like me to wait for you to finish those other lines, I can merge this now and merge the last 300+ later in another PR if you want.

More additions can be done in later PR's if you want as you find time.

**Pull request merged**
