### PR TITLE
orescaner for tileentity ore (1/2)

### PR DESCRIPTION
**Pull request by netherever**

### CODE REVIEW

**Comment by jrddunbr** [comment]
I'll look at this when I get home today from work.

**Comment by netherever** [comment]
Had some idea about this.
Will fix for tfc ore only.

**Comment by netherever** [comment]
hope it works

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.

**Pull request closed without merging**
