### PR TITLE
added energy meter webhook API including powering on/off with status codes.

### PR DESCRIPTION
**Pull request by jrddunbr**
Status codes:

200: do nothing
202: turn on
205: reset counters
402: turn off

### CODE REVIEW

**Comment by jrddunbr** [comment]
Todo: fix GUI

**Comment by Grissess** [comment]
This seems like it could easily be a bad idea; setting up and tearing down TCP connections in any IProcess is fairly heavy, and the processes are run serially. I'd check this very carefully for performance issues. (If there are any, might I recommend having a dedicated thread and a queue-like communication channel to handle that network traffic?)

**Comment by jrddunbr** [comment]
I threaded it I'm pretty sure (at least locally), but yes, I'm aware that
building up and taking down a HTTP response could take multiple seconds.

**Comment by jrddunbr** [comment]
Yeah, L611 in that commit starts a thread. I am not too concerned about race conditions.. should be OK? I may want to make it call the switch function later.

**Comment by jrddunbr** [comment]
@Grissess any thoughts before I merge?

**Comment by jrddunbr** [comment]
@Grissess final call :D

**Comment by Grissess** [comment]
Woah now, are you creating a thread per Element? That's better than a thread per tick, but threads are a finite resource, and I'd shudder to think about loading a world that had thousands of such meters in it :P

**Comment by jrddunbr** [comment]
The thread is stopped when the simulation stops. Besides that, If I had to guess, it may just get disposed of automatically.

You haven't met OpenComputers then. They spawn tons of threads per computer. I can lower it I guess by having one, but that's a lot of variable passing, and I would rather spread out the load over a few ticks. It spends most of it's time sleeping anyway

**Comment by Grissess** [comment]
Having a couple threads in an IO-bound application is not a bad idea, but it shouldn't depend, e.g., on how many meters there are in the world. Have you thought about having a static, fixed-size thread pool which is communicated to by each meter?

**Comment by jrddunbr** [comment]
It sounds like more work than it's worth. We consume far more resources elsewhere than a few IO wait heavy threads that otherwise don't do much. I doubt this feature will see too many meters, and it will be disabled by default anyhow.

I would either keep it as it is or have just 1 new thread do it all.

**Comment by Grissess** [comment]
Fine :P

Make improving it a good enhancement, then :P

**Pull request merged**
