### PR TITLE
The Great Haxorian Megapatch

### PR DESCRIPTION
**Pull request by OmegaHaxors**
Reduced costs of recipes across the board.

Iron and Copper ingots now craft into twice as many cables
One rubber and two cables now make 2 Low Voltage/Signal Cables
Ingot recipe for cables now produces 12 cables from 6 rubber and 3 ingots
This doubles the crafting yield of ingots and rubber
Almost all iron has been replaced with iron cable in recipes
This includes the infamous Machine Block which used to take an unacceptable 8 iron now only takes 2
The exception is solar panels, the water turbine and power storage. I didn't want to make those too easy
Thankfully though all the iron you'll save on everything else should allow you to make them anyway
This one might be unpopular: Alloy ingot now requires two gold dust instead of two iron dust
This is effectively a nerf to the rarity of Alloy ingot but finally gives purpose to gold
The Cheap Ferromagnetic core now requires cables instead of ingots
The Average core has the same recipe
The Perfect core is now two plates more expensive
Standardized Heating Corps. You now craft the smallest version with cables, then merge them to upgrade.

All of this should prevent the horrible perma-poverty feeling you get in singleplayer, and dramatically reduce the amount of players only engaging with this mod in Creative mode.

### CODE REVIEW

**Comment by jrddunbr** [comment]
I haven't read an ounce of the code yet. Busy week ahead. But, briefly, while I have some quick thoughts:

* Twice the cables: OK
* One rubber and two cables make twice the wires: OK
* Signal Cable recipie: OK
* Will have to look closer at the substitutions for iron with iron cable, machine block
* Alloy ingot - I feel that a mix of tungsten dust, gold dust, coal dust, and iron dust would be better. Some further discussion perhaps on this one. Removing iron entirely makes it feel less like a alloy and makes it feel like it isn't worth anything but a hodge-podge. Perhaps looking into the uses of alloy ingot may be a good idea here. Alloy ingot rarity may not be a bad thing.
* Cores: OK
* Heating cores: Will have to look at closer

@Grissess thoughts?

**Comment by OmegaHaxors** [comment]
> * Alloy ingot - I feel that a mix of tungsten dust, gold dust, coal dust, and iron dust would be better. Some further discussion perhaps on this one. Removing iron entirely makes it feel less like a alloy and makes it feel like it isn't worth anything but a hodge-podge. Perhaps looking into the uses of alloy ingot may be a good idea here. Alloy ingot rarity may not be a bad thing.

Regarding that, I've playtested it for awhile and the general feeling i'm getting is that tungsten is too common since the change. It's probably worth redoing the recipe to be more expensive on tungsten and re-introducing the iron component again. Everything outside of the excess in tungsten is particularly fair though, especially considering there is no longer a massive iron bottleneck.

Reducing the machine block to require a 4th of the iron at first felt a little bit too much, but after being able to use iron for non-ELN purposes, as well as thing such as signal wires, I won't be increasing the iron requirement for that at all. It would just slide everything back into poverty territory again. I would like to somewhat increase the cost of the machine block, but I can't exactly think of any resource that would make sense and would also be obtainable in the early game.

**Comment by jrddunbr** [comment]
Machine block with copper ore corners and iron cable edges may work

**Comment by OmegaHaxors** [comment]
I don't exactly want unprocessed resources to be in any recipe, otherwise you're going to run into situations where you process all of a resource only to find out you need it for something. I hate that.

Tree resin (as an epoxy) would be a good fit. It's easy to obtain early game and not too much of a pain.

**Comment by Grissess** [comment]
This is going to be quite a change from upstream! Not that we're looking to maintain perfect compatibility with them, of course, but staying similar *enough* to ease merging the eventual 1.10+ ports was on the back of my mind. Of course, I've heard there are enough breaking changes in that port anyway, so it's not like it won't be hard in general.

@jrddunbr Should we pull in whatever's on upstream's 1.7.10 tip? We can try to minimize the differences before merging this in, so it will be easy to PR to them if desired.

I'm ambivalent on the recipes; of all the tech mods I've tried, ELN is consistently one of the cheapest, though the iron bottleneck is definitely felt far and wide in one of our current SMP servers. (ELN is certainly not the only one that hits iron so hard, though.) Do we want this gated through a config before merging, or should this be accepted as the official new set of recipes?

**Comment by jrddunbr** [comment]
@Grissess Upstream's tip doesn't have a lot of changes except for the license file contraption. To be honest, most of the changes would have to be merged manually later, best we just make this really good and then merge all of the features in the most sensible way later.

As for your question about balance - heck, we're a fork. We *can* make decisions to try and balance the mod, and if we decide that those are no better, it's easier to change later to something else, and if it's good enough, then it will be something that is desired to be merged upstream when the time comes. I don't think that a config helps the problem much, it just adds another layer of complication.

@OmegaHaxors I agree with the iron argument - that's a lot of iron. I suppose that if I didn't déteste the alarm sound(s) as much that I'd be upset about the number of iron required for those. There are still other recipies (such as many of the logic circuits) which are completely illogical. Heck, we could use nuggets for some thing like OpenComputers does.

The flywheel should likely be further changed; I may make a lead block. This all depends on if the balance is weird for the next update to shafts though, so I'll wait...

**Comment by jrddunbr** [comment]
Can we add a new recipe to make the optimal ferromagnetic core more easily? The extra step of moving the cores around in one's crafting bench when making the standard core is unnecessary micro-crafting IMO.

**Comment by OmegaHaxors** [comment]
> Can we add a new recipe to make the optimal ferromagnetic core more easily? The extra step of moving the cores around in one's crafting bench when making the standard core is unnecessary micro-crafting IMO.

Sure. I don't mind cutting out a little microcrafting grind. As long as the cost is about the same, resource-wise.

**Comment by OmegaHaxors** [comment]
This is getting a little out of hand, it was only supposed to be a few changes now i'm changing the whole mod. Thankfully, i'm going to be on vacation soon so that will give everyone a chance to review the changes. I'll try to abstain from uploading any new mechanics until review is finished, and stick mostly to bug fixes.

**Comment by OmegaHaxors** [comment]
Closed due to rebasing. I'll put up the new one (it will be a lot cleaner) when it's ready.

**Comment by jrddunbr** [comment]
Mk

**Pull request closed without merging**
