### PR TITLE
some progress

### PR DESCRIPTION
**Pull request by jrddunbr**
Working on Issue #5 

The colors are somewhat there. I'm having a difficult problem with getting them in order. I suspect either Waila is strange and does things out of order, or my math skills are poor (but it could be both!)

Waila doesn't work with newlines, you need to have next line's items in the list (which needs a non duplicated key name for a map?). Thus, I split the cable into 4 "channels".

### CODE REVIEW

**Comment by Grissess** [comment]
"groups" would be a better term :)

I assume you're giving #5 to me to continue work on this branch?

**Comment by jrddunbr** [comment]
Yeah

**Comment by jrddunbr** [comment]
Is that change all that's required?

**Comment by Grissess** [comment]
@jrddunbr I believe so. Pull the branch and test! :)

**Comment by jrddunbr** [comment]
Got to check the commit to see if the channels order properly.

**Pull request merged**
